---
title: "Vota Unicamp!"
author: "Benilton S Carvalho"
runtime: shiny
output: html_document
---

```{r codigo_wordcloud}
#Site que proveu a função abaixo
#http://www.sthda.com/english/wiki/word-cloud-generator-in-r-one-killer-function-to-do-everything#-you-need

#++++++++++++++++++++++++++++++++++
# rquery.wordcloud() : Word cloud generator
# - http://www.sthda.com
#+++++++++++++++++++++++++++++++++++
# x : character string (plain text, web url, txt file path)
# type : specify whether x is a plain text, a web page url or a file path
# lang : the language of the text
# excludeWords : a vector of words to exclude from the text
# textStemming : reduces words to their root form
# colorPalette : the name of color palette taken from RColorBrewer package, 
# or a color name, or a color code
# min.freq : words with frequency below min.freq will not be plotted
# max.words : Maximum number of words to be plotted. least frequent terms dropped

# value returned by the function : a list(tdm, freqTable)
rquery.wordcloud <- function(x, type=c("text", "url", "file"), 
                             lang="english", excludeWords=NULL, 
                             textStemming=FALSE,  colorPalette="Dark2",
                             min.freq=3, max.words=200)
{ 
  library("tm")
  library("SnowballC")
  library("wordcloud")
  library("RColorBrewer") 
  
  if(type[1]=="file") text <- readLines(x)
  else if(type[1]=="url") text <- html_to_text(x)
  else if(type[1]=="text") text <- x
  
  # Load the text as a corpus
  docs <- Corpus(VectorSource(text))
  # Convert the text to lower case
  docs <- tm_map(docs, content_transformer(tolower))
  # Remove numbers
  docs <- tm_map(docs, removeNumbers)
  # Remove stopwords for the language 
  docs <- tm_map(docs, removeWords, stopwords(lang))
  # Remove punctuations
  docs <- tm_map(docs, removePunctuation)
  # Eliminate extra white spaces
  docs <- tm_map(docs, stripWhitespace)
  # Remove your own stopwords
  if(!is.null(excludeWords)) 
    docs <- tm_map(docs, removeWords, excludeWords) 
  # Text stemming
  if(textStemming) docs <- tm_map(docs, stemDocument)
  # Create term-document matrix
  tdm <- TermDocumentMatrix(docs)
  m <- as.matrix(tdm)
  v <- sort(rowSums(m),decreasing=TRUE)
  d <- data.frame(word = names(v),freq=v)
  # check the color palette name 
  if(!colorPalette %in% rownames(brewer.pal.info)) colors = colorPalette
  else colors = brewer.pal(8, colorPalette) 
  # Plot the word cloud
  set.seed(1234)
  wordcloud(d$word,d$freq, min.freq=min.freq, max.words=max.words,
            random.order=FALSE, rot.per=0.35, 
            use.r.layout=FALSE, colors=colors)
  
  invisible(list(tdm=tdm, freqTable = d))
}

#++++++++++++++++++++++
# Helper function
#++++++++++++++++++++++
# Download and parse webpage
html_to_text<-function(url){
  library(RCurl)
  library(XML)
  # download html
  html.doc <- getURL(url)  
  #convert to plain text
  doc = htmlParse(html.doc, asText=TRUE)
  # "//text()" returns all text outside of HTML tags.
  # We also don’t want text such as style and script codes
  text <- xpathSApply(doc, "//text()[not(ancestor::script)][not(ancestor::style)][not(ancestor::noscript)][not(ancestor::form)]", xmlValue)
  # Format text vector into one character string
  return(paste(text, collapse = " "))
}

```

## Setup

```{r input, message=FALSE}
#Sys.setlocale(locale='UTF-8')
Sys.setlocale(category = "LC_TIME", locale="Portuguese_Brazil.1252")
library(stringr)
library(rvest)
library(googleVis)
library(leaflet)
page = read_html('http://votaunicamp.herokuapp.com/results/')
tbl = html_table(page)[[2]]
names(tbl)=c("Curso","Total","Sim","Abstenção","Não")
tbl$Curso=repair_encoding(tbl$Curso)
head(tbl)
```

## Formatação de Dados

```{r format}
mytbl = data.frame(codigo=as.integer(str_extract(tbl$Curso, "^\\d+")),
                   nivel=NA,
                   curso=gsub("^(\\d+) - (.*)$", "\\2", tbl$Curso),
                   total=tbl$Total,
                   sim=as.integer(str_extract(tbl$Sim, "^\\d+")),
                   nao=as.integer(str_extract(tbl$Não, "^\\d+")),
                   abstencao=as.integer(str_extract(tbl$Abstenção, "^\\d+")))
nivel = str_extract(mytbl$curso, "(Dou|Mes)[a-z]+")
nivel[grepl("Mes", nivel)] = "Mestrado"
nivel[grepl("Dou", nivel)] = "Doutorado"
nivel[is.na(nivel)] = "Graduacao"
mytbl$nivel = nivel
rm(nivel)
mytbl$curso = gsub("(Mes|Dou).+ em (.*)$", "\\2", mytbl$curso)
head(mytbl)
```

## Gráfico de barras

``` {r barras}
barplot(c(sum(mytbl$sim),sum(mytbl$nao),sum(mytbl$abstencao)),legend=colnames(mytbl[5:7]),col=c("gold1","darkorchid2","antiquewhite2"),ylab = "Frequência", main =  "Total de Votos")

```

```{r }
library(d3heatmap)
library(RColorBrewer)
d3heatmap(mytbl[5:7],col=rev(brewer.pal(12,"Paired")),yaxis_width = 200)
```

```{r,echo=FALSE,message=FALSE}

selectInput("curso","Escolha o curso desejado:", choices=seq(1,nrow(mytbl),1))

#textInput("curso","Escolha o curso desejado:",)
```

```{r,echo=FALSE,message=FALSE}
renderPlot(barplot(as.integer(mytbl[as.integer(input$curso),5:7]),main="Total de votos por curso",ylab="Frequência",legend=colnames(mytbl[5:7]),col=c("gold1","darkorchid2","antiquewhite2"),ylim=c(0,max(as.integer(mytbl[as.integer(input$curso),5:7])))))
options=list(width="100%", height="100%")
```



## Gauge Plots

```{r plot_gauge}
tbl0 = subset(mytbl, nivel=='Graduacao')
tbl0$pnao = round(tbl0$nao/tbl0$total*100, 0)
gauge = gvisGauge(tbl0[, c('curso', 'pnao')], 'curso', 'nao',
                  options=list(min=0, max=100, greenFrom=0,
                                 greenTo=20, yellowFrom=40, yellowTo=60,
                                 redFrom=80, redTo=100, width=400, height=300))
plot(gauge)
```

## Obtenção de Dados Geográficos

Obter localizações (lat/lon) por meio do OpenStreet Maps:

- Abrir OpenStreet Maps (OSM) em (http://www.openstreetmap.org/#map=16/-22.8173/-47.0677)
- Dar zoom máximo no instituto de interesse
- Olhar o endereço na barra de endereço após o zoom
- Atualizar o data.frame abaixo com as informações

```{r enderecos}
ends = data.frame(instituto=c('IMECC', 'FEM', 'FEF'),
           lat=c(-22.81583,-22.81938,-22.81476),
           lon=c(-47.06769,-47.06592,-47.07333))
map = leaflet()
map = addTiles(map)
map = addCircleMarkers(map, lat=ends$lat, lng=ends$lon, popup = ends$instituto)
map
```

## Intervalos de Confiança

```{r stats}
p = with(mytbl, nao/(total))
mes = qnorm(.975)*sqrt(1/(4*mytbl$total))
ics = cbind(pmax(p-mes, 0), pmin(p+mes, 1))
colnames(ics) = c("lower", "upper")
mytbl$p = p
mytbl = cbind(mytbl, ics)
```
